from .client import llm_client
from .prompts import (
    CV_ANALYSIS_SYSTEM_PROMPT,
    CV_ANALYSIS_USER_TEMPLATE,
    INTERVIEW_START_SYSTEM_PROMPT,
    INTERVIEW_START_USER_TEMPLATE,
    INTERVIEW_FEEDBACK_SYSTEM_PROMPT,
    INTERVIEW_FEEDBACK_USER_TEMPLATE,
    CV_SINGLE_PASS_SYSTEM_PROMPT,
    CV_SINGLE_PASS_POSITION_USER_TEMPLATE,
    CV_SINGLE_PASS_JD_USER_TEMPLATE,
    CV_EVALUATION_WITH_CRITERIA_SYSTEM_PROMPT,
    CV_EVALUATION_WITH_CRITERIA_USER_TEMPLATE,
)

__all__ = [
    "llm_client",
    "CV_ANALYSIS_SYSTEM_PROMPT",
    "CV_ANALYSIS_USER_TEMPLATE",
    "INTERVIEW_START_SYSTEM_PROMPT",
    "INTERVIEW_START_USER_TEMPLATE",
    "INTERVIEW_FEEDBACK_SYSTEM_PROMPT",
    "INTERVIEW_FEEDBACK_USER_TEMPLATE",
    "CV_SINGLE_PASS_SYSTEM_PROMPT",
    "CV_SINGLE_PASS_POSITION_USER_TEMPLATE",
    "CV_SINGLE_PASS_JD_USER_TEMPLATE",
    "CV_EVALUATION_WITH_CRITERIA_SYSTEM_PROMPT",
    "CV_EVALUATION_WITH_CRITERIA_USER_TEMPLATE",
]

